import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'
import './globals.css'
import AuthContext from '@/app/context/AuthContext'
import ProgressBarProvider from '@/components/providers/progressbar-provider'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { Toaster } from '@/components/ui/toaster'
import ModalProvider from '@/components/providers/modal-provider'
import { cn } from '@/lib/utils'
import { SocketProvider } from '@/components/providers/socket-provider'

const inter = Noto_Sans({ subsets: ['latin'], weight: "400" })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "bg-white dark:bg-dark-primary")}>
        <AuthContext>
          <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey="neptune-theme">
            <SocketProvider>
              <ProgressBarProvider>
                <ModalProvider />
                {children}
                <Toaster />
              </ProgressBarProvider>
            </SocketProvider>
          </ThemeProvider>
        </AuthContext>
      </body>
    </html>
  )
}
